baseURL = "https://diggajupadhyay.github.io/"
languageCode = "en-us"
title = "Diggaj Upadhyay"
theme = "digup-lightweight-portfolio"

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"
    lineNos = false
    lineNumbersInTable = false
